### PR TITLE
Add brackets autoclose and highlighting

### PR DESCRIPTION
**Pull request by manparvesh**
As mentioned in #9

### CODE REVIEW

**Comment by rmnoon** [comment]
This looks really nice: thanks for submitting!  Did you test that it works nicely with syncing?

**Comment by manparvesh** [comment]
Yes, it works with the syncing as well.

**Comment by manparvesh** [comment]
There seem to be several other options available in codemirror that can be used to make this project even more interesting! I wanted to try some more features, but didn't have much time. You should take a look at the list

**Comment by rmnoon** [comment]
Cool, just merged this guy.  I'll try and run a release soon.

**Comment by rmnoon** [comment]
Just ran a release (I think I did while in May as well) so this should be live.

**Pull request merged**
